package:
  name: pysamstats
  version: 1.0.1

source:
  fn: v1.0.1.tar.gz
  url: https://github.com/alimanfoo/pysamstats/archive/v1.0.1.tar.gz
  md5: db8a5ad0db0027f55fd954a5510a797a

build:
  number: 0
#  skip: True # [osx or not py35 or not py27]

requirements:
  build:
    - python
    - cython
    - pysam >=0.11
    - zlib
    - gcc

  run:
    - python
    - pysam >=0.11
    - zlib
    - libgcc
    - numpy
    - pytables

test:
  requires:
    - nose
  source_files:
    - fixture
  imports:
    - pysamstats
  commands:
    - $PYTHON -m nose -v pysamstats
#    - pysamstats --help
#    - pysamstats --type coverage fixture/test.bam > coverage.txt
#    - pysamstats --type coverage --output=coverage.txt fixture/test.bam
#    - pysamstats --type coverage --output=coverage.h5 --format=hdf5 fixture/test.bam
#    - pysamstats --type coverage --fields=pos,reads_all fixture/test.bam > coverage_fields.txt
#    - pysamstats --type coverage_binned --fasta=fixture/ref.fa fixture/test.bam > coverage_binned.txt
#    - pysamstats --type coverage_binned --fasta=fixture/ref.fa --output=coverage_binned.txt fixture/test.bam
#    - pysamstats --type coverage_binned --fasta=fixture/ref.fa --output=coverage_binned.h5 --format=hdf5 fixture/test.bam
#    - pysamstats --type=coverage --min-mapq=27 --min-baseq=17 --no-dup --no-del fixture/test.bam > coverage_filtered.txt
#    - pysamstats --type=coverage_binned --fasta=fixture/ref.fa --min-mapq=27 --no-dup fixture/test.bam > coverage_binned_filtered.txt

about:
  home: https://github.com/alimanfoo/pysamstats
  license: MIT
  summary: A Python utility for calculating statistics against genome position based on sequence alignments from a SAM, BAM or CRAM file.
